import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
    <table className="ouuterTable" style={{width: '100%', border:"0", cellspacing:"0", cellpadding:"0"}}>
        <tr>
            <td>
                <table className="innerTable" style={{margin:"0", width:"600px", border:"0", cellspacing:"0", cellpadding:"0"}}>
                    {/* First Row */}
                    <tr>
                      <td>
                          <header> 
                            <div className="header-Title">
                              <h1>Walmart</h1>
                              <img src="https://cutewallpaper.org/21/walmart-logo-no-background/D-Cartoon-Icons-II-Windows-Restart-Walmart-logo-.jpg"/>
                            </div>

                            <div className="header-Links">
                              <a href="#">Vist Walmart.com</a>
                              <a href="#">Help</a>
                              <a href="#">My Account</a>
                            </div>

                          </header>
                      </td>
                  </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

      
    </div>
    
  )
}
